apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: robin-personal-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 40
    ssh:
      allow: true
      publicKeyName: eks-ohio